version: '3'

services:

  app:
    build: docker/app/
    volumes:
      - ./:/srv/app/
    env_file:
      - ./docker/.docker.env
    ports:
      - "80:80"
    working_dir: /srv/app/

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./docker/.docker.env
    ports:
      - "3306:3306"
